site_name: poetry-the-first
repo_url: https://github.com/BrandonDing/poetry-the-first
site_url: https://BrandonDing.github.io/poetry-the-first
site_description: This is test project for poetry!
site_author: Brandon Ding
edit_uri: edit/main/docs/
repo_name: BrandonDing/poetry-the-first
copyright: Maintained by <a href="https://BrandonDing.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/BrandonDing/poetry-the-first
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/poetry-the-first

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true